export type { BonusState } from "./domain/bonusRules";
export { createBattleHand, createCardCollection, createDeck, selectBattleCardIds } from "./domain/decks";
export { getAvailableCards, getSelectedCard, getUsedIds, makeFighter, refreshBattleHand } from "./domain/fighters";
export { applyOutcome, buildRewards, createInitialGame, createRound, getMatchResult, otherSide, startNextRound } from "./domain/match";
export { chooseEnemyMove, getEnemyPreview } from "./domain/opponentStrategy";
export type { EnemyMove } from "./domain/opponentStrategy";
export { resolveRound } from "./domain/roundResolver";
export type { ScoreOptions, ScoreResult } from "./domain/scoring";
export { hasApplicableAbilityEffect, isAbilityBlocked, score } from "./domain/scoring";
export { aiOpponents, selectAiOpponent } from "./loadouts";
export type { AiOpponent } from "./loadouts";
