import type { AiDifficulty, AiStyle, FighterAiProfile } from "./types";

export const playerCollectionIds = [
  "alpha",
  "alpha-nikolay",
  "fury",
  "micron",
  "dahack",
  "dahack-110",
  "aliens",
  "aliens-392",
  "fury-179",
  "chasers-738",
  "enigma-358",
  "metropolis-465",
  "metro",
  "enigma",
  "toyz",
  "toyz-schelkunchik",
];

export const playerDeckIds = [
  "alpha",
  "alpha-nikolay",
  "fury",
  "micron",
  "dahack",
  "dahack-110",
  "aliens",
  "aliens-392",
  "fury-179",
  "chasers-738",
  "enigma-358",
  "metropolis-465",
  "metro",
  "enigma",
  "toyz",
  "toyz-schelkunchik",
];

export type AiOpponent = {
  id: string;
  name: string;
  title: string;
  level: number;
  difficulty: AiDifficulty;
  style: AiStyle;
  aggression: number;
  riskTolerance: number;
  collectionIds: string[];
  deckIds: string[];
};

export const aiOpponents: AiOpponent[] = [
  {
    id: "sparring-operator",
    name: "Оператор Нуль",
    title: "Рівень 1 · навчальна сітка",
    level: 1,
    difficulty: "rookie",
    style: "balanced",
    aggression: 0.35,
    riskTolerance: 0.25,
    collectionIds: [
      "metropolis-396",
      "metropolis-301",
      "metropolis-1186",
      "metropolis-497",
      "workers-446",
      "workers-461",
      "workers-659",
      "workers-1533",
      "toyz-1276",
      "toyz-1279",
      "toyz-1511",
      "toyz-1746",
    ],
    deckIds: [
      "metropolis-396",
      "metropolis-301",
      "metropolis-1186",
      "metropolis-497",
      "workers-446",
      "workers-461",
      "workers-659",
      "workers-1533",
      "toyz-1276",
      "toyz-1279",
      "toyz-1511",
      "toyz-1746",
    ],
  },
  {
    id: "ash-runner",
    name: "Іскра Раннер",
    title: "Рівень 2 · швидкий тиск",
    level: 2,
    difficulty: "adept",
    style: "aggressive",
    aggression: 0.58,
    riskTolerance: 0.42,
    collectionIds: [
      "fury-1429",
      "fury-482",
      "fury-1658",
      "fury-890",
      "alpha-272",
      "alpha-858",
      "alpha-438",
      "alpha-365",
      "chasers-867",
      "chasers-1674",
      "chasers-732",
      "chasers-1217",
    ],
    deckIds: [
      "fury-1429",
      "fury-482",
      "fury-1658",
      "fury-890",
      "alpha-272",
      "alpha-858",
      "alpha-438",
      "alpha-365",
      "chasers-867",
      "chasers-1674",
      "chasers-732",
      "chasers-1217",
    ],
  },
  {
    id: "signal-warden",
    name: "Вартовий Сигналу",
    title: "Рівень 3 · контроль бонусів",
    level: 3,
    difficulty: "adept",
    style: "control",
    aggression: 0.42,
    riskTolerance: 0.32,
    collectionIds: [
      "aliens-598",
      "aliens-1679",
      "aliens-1013",
      "aliens-793",
      "dahack-468",
      "dahack-889",
      "dahack-1711",
      "dahack-194",
      "circus-253",
      "circus-718",
      "circus-569",
      "circus-484",
    ],
    deckIds: [
      "aliens-598",
      "aliens-1679",
      "aliens-1013",
      "aliens-793",
      "dahack-468",
      "dahack-889",
      "dahack-1711",
      "dahack-194",
      "circus-253",
      "circus-718",
      "circus-569",
      "circus-484",
    ],
  },
  {
    id: "tempo-smith",
    name: "Коваль Темпу",
    title: "Рівень 4 · економія енергії",
    level: 4,
    difficulty: "veteran",
    style: "tempo",
    aggression: 0.5,
    riskTolerance: 0.34,
    collectionIds: [
      "metropolis-590",
      "metropolis-787",
      "metropolis-1640",
      "metropolis-1545",
      "workers-401",
      "workers-403",
      "workers-594",
      "workers-1685",
      "micron-47",
      "micron-160",
      "micron-670",
      "micron",
    ],
    deckIds: [
      "metropolis-590",
      "metropolis-787",
      "metropolis-1640",
      "metropolis-1545",
      "workers-401",
      "workers-403",
      "workers-594",
      "workers-1685",
      "micron-47",
      "micron-160",
      "micron-670",
      "micron",
    ],
  },
  {
    id: "grave-accountant",
    name: "Некроаудитор",
    title: "Рівень 5 · виснаження",
    level: 5,
    difficulty: "veteran",
    style: "attrition",
    aggression: 0.46,
    riskTolerance: 0.3,
    collectionIds: [
      "damned-202",
      "damned-668",
      "damned-501",
      "damned-1462",
      "chasers-727",
      "chasers-1439",
      "chasers-1733",
      "chasers-1187",
      "saints-553",
      "saints-638",
      "saints-1522",
      "saints-216",
    ],
    deckIds: [
      "damned-202",
      "damned-668",
      "damned-501",
      "damned-1462",
      "chasers-727",
      "chasers-1439",
      "chasers-1733",
      "chasers-1187",
      "saints-553",
      "saints-638",
      "saints-1522",
      "saints-216",
    ],
  },
  {
    id: "mirror-archivist",
    name: "Архіваріус Дзеркал",
    title: "Рівень 6 · хамелеон",
    level: 6,
    difficulty: "veteran",
    style: "control",
    aggression: 0.5,
    riskTolerance: 0.5,
    collectionIds: [
      "enigma-1431",
      "enigma-1394",
      "enigma-710",
      "enigma-300",
      "psi-1128",
      "psi-589",
      "psi-582",
      "psi-1280",
      "nemos-1740",
      "nemos-1514",
      "nemos-1516",
      "nemos-154",
    ],
    deckIds: [
      "enigma-1431",
      "enigma-1394",
      "enigma-710",
      "enigma-300",
      "psi-1128",
      "psi-589",
      "psi-582",
      "psi-1280",
      "nemos-1740",
      "nemos-1514",
      "nemos-1516",
      "nemos-154",
    ],
  },
  {
    id: "street-croupier",
    name: "Вуличний Круп'є",
    title: "Рівень 7 · ризик і ставка",
    level: 7,
    difficulty: "elite",
    style: "aggressive",
    aggression: 0.7,
    riskTolerance: 0.68,
    collectionIds: [
      "gamblers-472",
      "gamblers-1456",
      "gamblers-673",
      "gamblers-632",
      "kingpin-1558",
      "kingpin-1657",
      "kingpin-661",
      "kingpin-669",
      "mafia-502",
      "mafia-1292",
      "mafia-1684",
      "mafia-540",
    ],
    deckIds: [
      "gamblers-472",
      "gamblers-1456",
      "gamblers-673",
      "gamblers-632",
      "kingpin-1558",
      "kingpin-1657",
      "kingpin-661",
      "kingpin-669",
      "mafia-502",
      "mafia-1292",
      "mafia-1684",
      "mafia-540",
    ],
  },
  {
    id: "factory-drummer",
    name: "Заводський Барабан",
    title: "Рівень 8 · натиск руки",
    level: 8,
    difficulty: "elite",
    style: "tempo",
    aggression: 0.62,
    riskTolerance: 0.42,
    collectionIds: [
      "toyz-1385",
      "toyz-1273",
      "toyz-1417",
      "toyz-1571",
      "street-914",
      "street-193",
      "street-1690",
      "street-70",
      "workers-1076",
      "workers-674",
      "workers-1457",
      "workers-405",
    ],
    deckIds: [
      "toyz-1385",
      "toyz-1273",
      "toyz-1417",
      "toyz-1571",
      "street-914",
      "street-193",
      "street-1690",
      "street-70",
      "workers-1076",
      "workers-674",
      "workers-1457",
      "workers-405",
    ],
  },
  {
    id: "bio-herald",
    name: "Біо-Герольд",
    title: "Рівень 9 · мутація",
    level: 9,
    difficulty: "elite",
    style: "attrition",
    aggression: 0.58,
    riskTolerance: 0.52,
    collectionIds: [
      "symbio-1698",
      "symbio-1708",
      "symbio-1639",
      "symbio-1646",
      "deviants-137",
      "deviants-266",
      "deviants-1519",
      "deviants-1720",
      "damned-1157",
      "damned-222",
      "damned-791",
      "damned-202",
    ],
    deckIds: [
      "symbio-1698",
      "symbio-1708",
      "symbio-1639",
      "symbio-1646",
      "deviants-137",
      "deviants-266",
      "deviants-1519",
      "deviants-1720",
      "damned-1157",
      "damned-222",
      "damned-791",
      "damned-202",
    ],
  },
  {
    id: "nexus-grandmaster",
    name: "Грандмайстер Нексусу",
    title: "Рівень 10 · фінальний протокол",
    level: 10,
    difficulty: "champion",
    style: "balanced",
    aggression: 0.72,
    riskTolerance: 0.62,
    collectionIds: [
      "alpha-630",
      "aliens-392",
      "dahack-110",
      "fury-565",
      "gamblers-706",
      "kingpin-644",
      "metropolis-465",
      "enigma-236",
      "saints-455",
      "street-1401",
      "workers-406",
      "caliphate-816",
    ],
    deckIds: [
      "alpha-630",
      "aliens-392",
      "dahack-110",
      "fury-565",
      "gamblers-706",
      "kingpin-644",
      "metropolis-465",
      "enigma-236",
      "saints-455",
      "street-1401",
      "workers-406",
      "caliphate-816",
    ],
  },
];

export const enemyCollectionIds = aiOpponents[0].collectionIds;
export const enemyDeckIds = aiOpponents[0].deckIds;

export function selectAiOpponent(opponentId?: string) {
  if (opponentId) {
    return aiOpponents.find((opponent) => opponent.id === opponentId) ?? aiOpponents[0];
  }

  return aiOpponents[randomIndex(aiOpponents.length)];
}

export function toFighterAiProfile(opponent: AiOpponent): FighterAiProfile {
  return {
    opponentId: opponent.id,
    level: opponent.level,
    difficulty: opponent.difficulty,
    style: opponent.style,
    aggression: opponent.aggression,
    riskTolerance: opponent.riskTolerance,
  };
}

function randomIndex(maxExclusive: number) {
  const cryptoApi = globalThis.crypto;

  if (cryptoApi?.getRandomValues) {
    const values = new Uint32Array(1);
    const maxUint32 = 0xffffffff;
    const limit = maxUint32 - (maxUint32 % maxExclusive);

    do {
      cryptoApi.getRandomValues(values);
    } while (values[0] >= limit);

    return values[0] % maxExclusive;
  }

  return Math.floor(Math.random() * maxExclusive);
}
